import type { Flags, LocationId, Scene } from './types'
import { bg, cut, PROC } from './types'

export const ALLEY_CLUES = ['SUNDAY', 'UNDER THE SPIRAL', "WHO'S GOT A"] as const

export const SCENES: Record<LocationId, Scene> = {
  map: {
    id: 'map',
    title: 'THE WASTED CITY',
    hint: 'click what calls to you',
    bg: bg('the-wasted-city'),
    hotspots: [
      {
        id: 'map-library',
        src: cut('empty-bookshelf'),
        x: 14,
        y: 10,
        w: 13,
        h: 32,
        z: 3,
        action: {
          type: 'inspect',
          text: 'shelves you cannot reach from this street.',
        },
      },
      {
        id: 'map-screen',
        src: cut('crt-transparent-screen'),
        x: 36,
        y: 14,
        w: 16,
        h: 28,
        z: 4,
        label: 'THE SCREEN',
        action: { type: 'go', to: 'screen' },
      },
      {
        id: 'map-tents',
        src: cut('4-tent-cluster'),
        x: 6,
        y: 38,
        w: 24,
        h: 32,
        z: 5,
        label: 'TENT CITY',
        action: { type: 'go', to: 'tents' },
      },
      {
        id: 'map-alley',
        src: cut('tv-stack'),
        x: 54,
        y: 34,
        w: 18,
        h: 34,
        z: 5,
        action: {
          type: 'inspect',
          text: 'the stack only hisses from this side.',
        },
      },
      {
        id: 'map-car',
        src: cut('wrecked-rusted-green-car'),
        x: 70,
        y: 56,
        w: 26,
        h: 28,
        z: 6,
        label: 'NEW CRASHED CAR',
        action: { type: 'go', to: 'car' },
      },
      {
        id: 'map-car-2',
        src: cut('wrecked-rusted-blue-car'),
        x: 78,
        y: 72,
        w: 16,
        h: 16,
        z: 4,
        opacity: 0.85,
        action: { type: 'go', to: 'car' },
      },
      {
        id: 'map-venue-locked',
        src: cut('moldy-closed-door'),
        x: 8,
        y: 70,
        w: 11,
        h: 24,
        z: 6,
        visible: f => !f.venueUnlocked,
        action: {
          type: 'inspect',
          text: 'chained from the inside. not the mouth you want.',
        },
      },
      {
        id: 'map-venue-open',
        src: cut('open-molded-door'),
        x: 8,
        y: 70,
        w: 12,
        h: 24,
        z: 6,
        visible: f => f.venueUnlocked,
        action: {
          type: 'inspect',
          text: 'still a decoy. the real door was in the static.',
        },
      },
      {
        id: 'map-graves',
        src: cut('graves-with-tree'),
        x: 78,
        y: 8,
        w: 20,
        h: 28,
        z: 2,
        opacity: 0.72,
        action: {
          type: 'inspect',
          text: 'they die three times. the last is when the name is spoken for the last time.',
        },
      },
      {
        id: 'map-spiral',
        src: `${PROC}/wgam-spiral-icon.webp`,
        x: 62,
        y: 6,
        w: 11,
        h: 20,
        z: 7,
        opacity: 0.35,
        action: {
          type: 'inspect',
          text: 'a mark the nots scratch into walls.',
        },
      },
      {
        id: 'map-angel',
        src: cut('gothic-angel-statue'),
        x: 88,
        y: 28,
        w: 10,
        h: 22,
        z: 3,
        opacity: 0.55,
        visible: f => f.chapelFound,
        action: {
          type: 'inspect',
          text: 'it followed you back to the street. it does not open a door.',
        },
      },
    ],
  },

  tents: {
    id: 'tents',
    title: 'TENT CITY',
    bg: bg('tent-city'),
    hotspots: [
      {
        id: 'tent-green',
        src: cut('green-tent'),
        x: 8,
        y: 28,
        w: 28,
        h: 48,
        z: 3,
        action: {
          type: 'inspect',
          text: 'a not lives here. the canvas still smells like rain that never came.',
        },
      },
      {
        id: 'tent-yellow',
        src: cut('yellow-tent'),
        x: 36,
        y: 34,
        w: 26,
        h: 42,
        z: 4,
        action: { type: 'rabbit' },
      },
      {
        id: 'tent-red',
        src: cut('red-tent'),
        x: 62,
        y: 30,
        w: 24,
        h: 44,
        z: 3,
        action: {
          type: 'inspect',
          text: 'numbers on wrists. jobs at birth. the spiral doctrine of 2071.',
        },
      },
      {
        id: 'tent-flyer',
        src: cut('flyer-paper'),
        x: 42,
        y: 62,
        w: 14,
        h: 22,
        z: 6,
        rotate: -8,
        action: {
          type: 'flag',
          flag: 'seenFlyer',
          text: 'underground. sunday. look for the spiral. they wear rabbit faces.',
        },
      },
      {
        id: 'tent-tv',
        src: cut('old-tv-transparent-screen'),
        x: 78,
        y: 52,
        w: 18,
        h: 22,
        z: 5,
        action: {
          type: 'footage',
          n: 1,
        },
      },
      {
        id: 'tent-rabbit',
        src: cut('white-rabbit-mask'),
        x: 48,
        y: 36,
        w: 8,
        h: 14,
        z: 8,
        visible: f => f.rabbitBlink,
        action: {
          type: 'inspect',
          text: 'it blinked. you were not supposed to see that.',
        },
      },
    ],
  },

  screen: {
    id: 'screen',
    title: 'THE SCREEN',
    bg: bg('the-screen'),
    hotspots: [
      {
        id: 'screen-one',
        src: cut('man-silohette'),
        x: 38,
        y: 18,
        w: 24,
        h: 48,
        z: 2,
        behind: true,
        opacity: 0.85,
        action: { type: 'puzzle', puzzle: 'crt' },
      },
      {
        id: 'screen-crt',
        src: cut('crt-transparent-screen'),
        x: 28,
        y: 12,
        w: 44,
        h: 70,
        z: 4,
        action: { type: 'puzzle', puzzle: 'crt' },
      },
      {
        id: 'screen-mask',
        src: cut('black-mask'),
        x: 72,
        y: 58,
        w: 12,
        h: 16,
        z: 5,
        visible: f => f.tuned2071,
        action: {
          type: 'inspect',
          text: 'men in black masks. the haves feast. shut the fuck up while they hate.',
        },
      },
      {
        id: 'screen-tv-footage',
        src: cut('old-tv-transparent-screen'),
        x: 6,
        y: 36,
        w: 14,
        h: 20,
        z: 4,
        action: { type: 'footage', n: 2 },
      },
      {
        id: 'screen-barrel',
        src: cut('red-oil-barrel'),
        x: 12,
        y: 62,
        w: 10,
        h: 22,
        z: 3,
        action: {
          type: 'inspect',
          text: 'the one never lies, never cries. he tiptoes behind your eyes.',
        },
      },
      {
        id: 'screen-alley',
        src: cut('tv-stack'),
        x: 74,
        y: 12,
        w: 22,
        h: 42,
        z: 5,
        label: 'DEAD CHANNEL',
        visible: f => f.tuned2071,
        action: { type: 'go', to: 'alley' },
      },
    ],
  },

  library: {
    id: 'library',
    title: 'THE LIBRARY',
    bg: bg('the-library'),
    hotspots: [
      {
        id: 'lib-shelf-1',
        src: cut('bookshelf-with-books'),
        x: 6,
        y: 10,
        w: 22,
        h: 70,
        z: 2,
        action: {
          type: 'inspect',
          text: 'maybe if we spent more time at the library instead of posting highlight reels.',
        },
      },
      {
        id: 'lib-shelf-2',
        src: cut('bookshelf-books'),
        x: 70,
        y: 8,
        w: 24,
        h: 72,
        z: 2,
        action: {
          type: 'inspect',
          text: 'banned spines. music theory with the pages torn out.',
        },
      },
      {
        id: 'lib-shelf-3',
        src: cut('bookshelf-books-2'),
        x: 52,
        y: 22,
        w: 16,
        h: 48,
        z: 3,
        action: {
          type: 'inspect',
          text: 'dust thick as doctrine.',
        },
      },
      {
        id: 'lib-book',
        src: cut('open-book'),
        x: 30,
        y: 48,
        w: 22,
        h: 28,
        z: 6,
        action: { type: 'flag', flag: 'readDoctrine' },
      },
      {
        id: 'lib-worn',
        src: cut('worn-open-book'),
        x: 38,
        y: 66,
        w: 16,
        h: 20,
        z: 5,
        action: {
          type: 'inspect',
          text: 'you are nothing just like the number on your wrist.',
        },
      },
      {
        id: 'lib-cover',
        src: `${PROC}/wgam-front-cover.webp`,
        x: 22,
        y: 70,
        w: 10,
        h: 16,
        z: 7,
        rotate: 12,
        action: { type: 'footage', n: 6 },
      },
      {
        id: 'lib-spiral',
        src: `${PROC}/wgam-spiral-icon.webp`,
        x: 44,
        y: 38,
        w: 8,
        h: 14,
        z: 8,
        opacity: 0.7,
        visible: f => f.readDoctrine,
        action: { type: 'go', to: 'chapel' },
      },
    ],
  },

  alley: {
    id: 'alley',
    title: 'DEAD CHANNEL',
    bg: bg('dead-channel'),
    hotspots: [
      {
        id: 'alley-library',
        src: cut('empty-bookshelf'),
        x: 2,
        y: 8,
        w: 14,
        h: 38,
        z: 4,
        label: 'THE LIBRARY',
        action: { type: 'go', to: 'library' },
      },
      {
        id: 'alley-stack',
        src: cut('tv-stack'),
        x: 28,
        y: 8,
        w: 36,
        h: 58,
        z: 3,
        action: { type: 'inspect', text: 'found footage. three mouths. one word.' },
      },
      {
        id: 'alley-tv-0',
        x: 32,
        y: 18,
        w: 10,
        h: 12,
        z: 6,
        action: { type: 'footage', n: 3 },
      },
      {
        id: 'alley-tv-1',
        x: 44,
        y: 22,
        w: 10,
        h: 12,
        z: 6,
        action: { type: 'footage', n: 4 },
      },
      {
        id: 'alley-tv-2',
        x: 50,
        y: 36,
        w: 10,
        h: 12,
        z: 6,
        action: { type: 'footage', n: 5 },
      },
      {
        id: 'alley-tv-old',
        src: cut('old-tv-transparent-screen'),
        x: 4,
        y: 48,
        w: 22,
        h: 28,
        z: 4,
        action: {
          type: 'inspect',
          text: 'plug me in. the cable is already bitten through.',
        },
      },
      {
        id: 'alley-scrap',
        src: cut('pile-of-scrap'),
        x: 72,
        y: 58,
        w: 22,
        h: 28,
        z: 3,
        action: { type: 'inspect', text: 'digital asbestos of the golden age.' },
      },
      {
        id: 'alley-scrap-2',
        src: cut('pile-of-scrap-2'),
        x: 8,
        y: 72,
        w: 16,
        h: 20,
        z: 2,
        action: { type: 'inspect', text: 'you get the scraps while they feast.' },
      },
      {
        id: 'alley-door-locked',
        src: cut('moldy-closed-door'),
        x: 78,
        y: 12,
        w: 16,
        h: 48,
        z: 5,
        visible: f => !f.venueUnlocked,
        action: { type: 'puzzle', puzzle: 'password' },
      },
      {
        id: 'alley-door-open',
        src: cut('open-molded-door'),
        x: 78,
        y: 12,
        w: 16,
        h: 48,
        z: 5,
        visible: f => f.venueUnlocked,
        action: { type: 'go', to: 'venue' },
      },
    ],
  },

  car: {
    id: 'car',
    title: 'NEW CRASHED CAR',
    bg: bg('new-crashed-car'),
    hotspots: [
      {
        id: 'car-wreck',
        src: cut('wrecked-rusted-car'),
        x: 18,
        y: 28,
        w: 48,
        h: 40,
        z: 3,
        action: {
          type: 'inspect',
          text: 'remember when you could buy gasoline anywhere. or were you too young?',
        },
      },
      {
        id: 'car-blue',
        src: cut('wrecked-rusted-blue-car'),
        x: 58,
        y: 42,
        w: 28,
        h: 28,
        z: 2,
        opacity: 0.9,
        action: {
          type: 'inspect',
          text: 'if you light it up it might be fun. we might have to run.',
        },
      },
      {
        id: 'car-red-barrel',
        src: cut('red-oil-barrel'),
        x: 8,
        y: 52,
        w: 10,
        h: 28,
        z: 4,
        action: {
          type: 'inspect',
          text: "it's not like it's gone. glitter burns while satan churns.",
        },
      },
      {
        id: 'car-yellow-barrel',
        src: cut('yellow-oil-barrel'),
        x: 78,
        y: 48,
        w: 12,
        h: 32,
        z: 4,
        action: {
          type: 'inspect',
          text: 'who\'s got a match?',
        },
      },
      {
        id: 'car-matchbox',
        src: cut('match-box'),
        x: 40,
        y: 64,
        w: 14,
        h: 10,
        z: 7,
        visible: f => !f.hasMatchbook,
        action: {
          type: 'flag',
          flag: 'hasMatchbook',
          text: 'a matchbook. dry enough. you pocket it.',
        },
      },
      {
        id: 'car-match',
        src: cut('match'),
        x: 44,
        y: 70,
        w: 8,
        h: 8,
        z: 8,
        visible: f => f.hasMatchbook,
        rotate: 30,
        action: { type: 'inspect', text: 'you already have what you need.' },
      },
    ],
  },

  chapel: {
    id: 'chapel',
    title: 'SPIRAL CHAPEL',
    bg: bg('spiral-chapel'),
    hotspots: [
      {
        id: 'chapel-graves',
        src: cut('graves-with-tree'),
        x: 0,
        y: 48,
        w: 40,
        h: 48,
        z: 2,
        action: {
          type: 'inspect',
          text: 'born to die never to fly. they are the haves. we are the nots.',
        },
      },
      {
        id: 'chapel-angel',
        src: cut('gothic-angel-statue'),
        x: 70,
        y: 8,
        w: 26,
        h: 70,
        z: 3,
        action: {
          type: 'inspect',
          text: 'when you meet your maker you will find out he is the taker.',
        },
      },
      {
        id: 'chapel-bones',
        src: cut('pile-of-bones'),
        x: 48,
        y: 58,
        w: 22,
        h: 32,
        z: 4,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-spiral',
        src: `${PROC}/wgam-spiral-icon.webp`,
        x: 36,
        y: 10,
        w: 28,
        h: 50,
        z: 5,
        action: { type: 'invert' },
      },
      {
        id: 'chapel-book',
        src: cut('open-book'),
        x: 28,
        y: 62,
        w: 16,
        h: 20,
        z: 6,
        action: {
          type: 'inspect',
          text: 'anointed with a job. children of the swine. crawl for your meals.',
        },
      },
    ],
  },

  venue: {
    id: 'venue',
    title: 'THE VENUE',
    bg: bg('the-venue'),
    hotspots: [
      {
        id: 'venue-spiral',
        src: `${PROC}/wgam-spiral-icon.webp`,
        x: 36,
        y: 4,
        w: 28,
        h: 48,
        z: 1,
        opacity: 0.45,
        action: { type: 'inspect', text: 'under the spiral. sunday. they found you.' },
      },
      {
        id: 'venue-rabbit-1',
        src: cut('white-rabbit-mask'),
        x: 16,
        y: 22,
        w: 18,
        h: 32,
        z: 4,
        action: { type: 'inspect', text: 'guitar. lead vox. match.' },
      },
      {
        id: 'venue-rabbit-2',
        src: cut('white-rabbit-mask'),
        x: 42,
        y: 18,
        w: 16,
        h: 30,
        z: 5,
        filter: 'contrast(1.15) brightness(0.9)',
        action: { type: 'inspect', text: 'bass. backing vox. no names here.' },
      },
      {
        id: 'venue-rabbit-3',
        src: cut('white-rabbit-mask'),
        x: 64,
        y: 24,
        w: 17,
        h: 30,
        z: 4,
        filter: 'grayscale(0.4)',
        action: { type: 'inspect', text: 'drums. the pulse under the doctrine.' },
      },
      {
        id: 'venue-glyph',
        src: `${PROC}/wgam-spiral-icon.webp`,
        x: 8,
        y: 70,
        w: 8,
        h: 12,
        z: 6,
        opacity: 0.8,
        visible: f => f.glyphUnlocked,
        action: {
          type: 'inspect',
          text: 'the three screens remembered you. do you want to dream with me?',
        },
      },
      {
        id: 'venue-striker',
        x: 28,
        y: 72,
        w: 44,
        h: 14,
        z: 8,
        action: { type: 'puzzle', puzzle: 'strike' },
      },
    ],
  },

  fire: {
    id: 'fire',
    title: 'THE FIRE',
    bg: bg('the-fire'),
    hotspots: [
      {
        id: 'fire-wide',
        src: cut('wide-fire'),
        x: 10,
        y: 18,
        w: 80,
        h: 70,
        z: 3,
      },
      {
        id: 'fire-camp',
        src: cut('camp-fire'),
        x: 38,
        y: 28,
        w: 24,
        h: 50,
        z: 4,
      },
      {
        id: 'fire-1',
        src: cut('fire-1'),
        x: 58,
        y: 22,
        w: 22,
        h: 48,
        z: 5,
        opacity: 0.85,
      },
    ],
  },
}

export const FOOTAGE_CAPTIONS: Record<number, string> = {
  1: 'the message. no pictures. no songs.',
  2: 'something illegal in the hiss. not a name yet.',
  3: ALLEY_CLUES[0],
  4: ALLEY_CLUES[1],
  5: ALLEY_CLUES[2],
  6: 'rabbit faces. a red spiral. the place has a name.',
}

export function sceneHotspots(id: LocationId, flags: Flags) {
  return SCENES[id].hotspots.filter(h => (h.visible ? h.visible(flags) : true))
}

export const DOCTRINE_TEXT =
  'THE SPIRAL DOCTRINE OF 2071. when you are born you are anointed with a job. you will do that job under the eyes of god. you have no choice. you are meek. a diagram of the spiral is drawn in the margin — it wants to be followed.'

const PARENT: Record<LocationId, LocationId | null> = {
  map: null,
  tents: 'map',
  screen: 'map',
  car: 'map',
  alley: 'screen',
  library: 'alley',
  chapel: 'library',
  venue: 'alley',
  fire: 'venue',
}

export function parentOf(id: LocationId): LocationId | null {
  return PARENT[id]
}
