import type { Flags, LocationId, Scene } from './types'
import { bg, cut, PROC } from './types'

export const SCENES: Record<LocationId, Scene> = {
  map: {
    id: 'map',
    title: 'THE WASTED CITY',
    hint: 'click what calls to you',
    bg: bg('the-wasted-city'),
    hotspots: [
      {
        id: 'map-screen',
        src: cut('crt-transparent-screen'),
        x: 40,
        y: 62,
        w: 8,
        h: 14,
        z: 6,
        label: 'THE SCREEN',
        screen: {
          src: cut('tv-static'),
          x: 12.63,
          y: 10.31,
          w: 76.52,
          h: 57.07,
        },
        action: { type: 'go', to: 'screen' },
      },
      {
        id: 'map-tents',
        src: cut('4-tent-cluster'),
        x: 6,
        y: 48,
        w: 24,
        h: 32,
        z: 5,
        label: 'TENT CITY',
        action: { type: 'go', to: 'tents' },
      },
      {
        id: 'map-alley',
        src: cut('tv-stack'),
        x: 54,
        y: 34,
        w: 18,
        h: 34,
        z: 5,
        visible: f => !f.tuned2071,
        action: {
          type: 'inspect',
          text: 'the tv stack only hisses from this side. something seems to be behind them...',
        },
      },
      {
        id: 'map-alley-open',
        src: cut('tv-stack'),
        x: 54,
        y: 34,
        w: 18,
        h: 34,
        z: 5,
        label: 'THE DEAD CHANNEL',
        visible: f => f.tuned2071,
        action: { type: 'go', to: 'alley' },
      },
      {
        id: 'map-car-blue',
        src: cut('wrecked-rusted-blue-car'),
        x: 68,
        y: 68,
        w: 13,
        h: 13,
        z: 5,
        action: { type: 'go', to: 'scrapyard' },
      },
      {
        id: 'map-car-green',
        src: cut('wrecked-rusted-green-car'),
        x: 77,
        y: 59,
        w: 21,
        h: 22,
        z: 6,
        label: 'THE SCRAPYARD',
        action: { type: 'go', to: 'scrapyard' },
      },
    ],
  },

  tents: {
    id: 'tents',
    title: 'TENT CITY',
    bg: bg('tent-city'),
    hotspots: [
      {
        id: 'tent-green',
        src: cut('green-tent'),
        x: 8,
        y: 28,
        w: 28,
        h: 48,
        z: 3,
        action: {
          type: 'inspect',
          text: 'a not lives here. the canvas still smells like rain that never came.',
        },
      },
      {
        id: 'tent-yellow',
        src: cut('yellow-tent'),
        x: 36,
        y: 34,
        w: 26,
        h: 42,
        z: 4,
        action: { type: 'rabbit' },
      },
      {
        id: 'tent-red',
        src: cut('red-tent'),
        x: 62,
        y: 30,
        w: 24,
        h: 44,
        z: 3,
        action: {
          type: 'inspect',
          text: 'a voice from inside whisper to you. "2071, the year it graced us. 2071, never forget... 2071"',
        },
      },
      {
        id: 'tent-flyer',
        src: cut('flyer-paper'),
        x: 46,
        y: 68,
        w: 7,
        h: 11,
        z: 6,
        rotate: -8,
        action: {
          type: 'flag',
          flag: 'seenFlyer',
          text: 'underground. sunday. look for the spiral. they wear rabbit faces.',
        },
      },
      {
        id: 'tent-tv',
        src: cut('old-tv-transparent-screen'),
        x: 73,
        y: 65,
        w: 7.2,
        h: 8.8,
        z: 6,
        action: {
          type: 'footage',
          n: 1,
        },
      },
      {
        id: 'tent-rabbit',
        src: cut('white-rabbit-mask'),
        x: 48,
        y: 36,
        w: 8,
        h: 14,
        z: 8,
        visible: f => f.rabbitBlink,
        action: {
          type: 'inspect',
          text: 'it blinked. you were not supposed to see that.',
        },
      },
    ],
  },

  screen: {
    id: 'screen',
    title: 'THE SCREEN',
    bg: bg('the-screen'),
    hotspots: [
      {
        id: 'screen-crt',
        src: cut('crt-transparent-screen'),
        x: 32.4,
        y: 19,
        w: 35.2,
        h: 56,
        z: 4,
        screen: {
          src: cut('tv-static'),
          x: 12.63,
          y: 10.31,
          w: 76.52,
          h: 57.07,
        },
        action: { type: 'puzzle', puzzle: 'crt' },
      },
      {
        id: 'screen-barrel',
        src: cut('red-oil-barrel'),
        x: 6,
        y: 59,
        w: 5,
        h: 11,
        z: 3,
        action: {
          type: 'inspect',
          text: 'the one never lies, never cries. he tiptoes behind your eyes.',
        },
      },
      {
        id: 'screen-tv-footage',
        src: cut('old-tv-transparent-screen'),
        x: 8,
        y: 60,
        w: 7,
        h: 10,
        z: 5,
        action: { type: 'footage', n: 2 },
      },
    ],
  },

  library: {
    id: 'library',
    title: 'THE LIBRARY',
    bg: bg('the-library'),
    hotspots: [
      {
        id: 'lib-shelf-1',
        src: cut('bookshelf-with-books'),
        x: 8,
        y: 20,
        w: 11,
        h: 35,
        z: 2,
        action: {
          type: 'inspect',
          text: 'it says "names and jobs, row after row. nobody here chose either."',
        },
      },
      {
        id: 'lib-row-1',
        src: cut('bookshelf-books'),
        x: 68,
        y: 48,
        w: 18,
        h: 11,
        z: 3,
        action: {
          type: 'inspect',
          text: 'it says "music theory. every page about sound has been torn out."',
        },
      },
      {
        id: 'lib-row-2',
        src: cut('bookshelf-books-2'),
        x: 74,
        y: 51,
        w: 16,
        h: 10,
        z: 4,
        action: {
          type: 'inspect',
          text: 'it says "these are the books they banned. the dust is the thickest here."',
        },
      },
      {
        id: 'lib-row-3',
        src: cut('bookshelf-books'),
        x: 70,
        y: 54,
        w: 17,
        h: 11,
        z: 5,
        flipX: true,
        action: {
          type: 'inspect',
          text: 'it says "music theory. every page about sound has been torn out."',
        },
      },
      {
        id: 'lib-row-4',
        src: cut('bookshelf-books-2'),
        x: 78,
        y: 56,
        w: 15,
        h: 9,
        z: 6,
        action: {
          type: 'inspect',
          text: 'it says "these are the books they banned. the dust is the thickest here."',
        },
      },
      {
        id: 'lib-row-5',
        src: cut('bookshelf-books'),
        x: 72,
        y: 58,
        w: 16,
        h: 10,
        z: 7,
        action: {
          type: 'inspect',
          text: 'it says "music theory. every page about sound has been torn out."',
        },
      },
      {
        id: 'lib-book',
        src: cut('open-book'),
        x: 26,
        y: 70,
        w: 11,
        h: 14,
        z: 6,
        rotate: -22,
        tiltX: 38,
        action: { type: 'flag', flag: 'readDoctrine' },
      },
      {
        id: 'lib-worn',
        src: cut('worn-open-book'),
        x: 52,
        y: 74,
        w: 8,
        h: 10,
        z: 5,
        rotate: 28,
        tiltX: 38,
        action: {
          type: 'inspect',
          text: 'it says "you are nothing. you are the number on your wrist."',
        },
      },
      {
        id: 'lib-cover',
        src: `${PROC}/wgam-front-cover.webp`,
        x: 16,
        y: 78,
        w: 5,
        h: 8,
        z: 7,
        rotate: 12,
        tiltX: 38,
        action: {
          type: 'inspect',
          text: 'an album cover...? it appears less worn than everything else',
        },
      },
      {
        id: 'lib-book-2',
        src: cut('worn-open-book'),
        x: 38,
        y: 76,
        w: 9,
        h: 11,
        z: 6,
        rotate: -40,
        tiltX: 38,
        action: {
          type: 'inspect',
          text: 'it says "music is illegal. if they find an instrument, they break the hands that held it."',
        },
      },
      {
        id: 'lib-book-3',
        src: cut('open-book'),
        x: 62,
        y: 71,
        w: 10,
        h: 12,
        z: 5,
        rotate: 15,
        tiltX: 38,
        action: {
          type: 'inspect',
          text: 'it says "they are the haves. we are the nots. that is the only law."',
        },
      },
      {
        id: 'lib-book-4',
        src: cut('worn-open-book'),
        x: 44,
        y: 80,
        w: 7,
        h: 9,
        z: 7,
        rotate: -8,
        tiltX: 38,
        action: {
          type: 'inspect',
          text: 'it says "you die three times. the last is when no one says your name."',
        },
      },
      {
        id: 'lib-spiral',
        src: `${PROC}/wgam-spiral-icon-animated.svg`,
        x: 46.2,
        y: 35.9,
        w: 7.68,
        h: 13.44,
        z: 8,
        spin: true,
        action: { type: 'go', to: 'chapel' },
      },
    ],
  },

  alley: {
    id: 'alley',
    title: 'DEAD CHANNEL',
    bg: bg('dead-channel'),
    hotspots: [
      {
        id: 'alley-library',
        src: cut('empty-bookshelf'),
        x: 13.5,
        y: 32,
        w: 7,
        h: 19,
        z: 4,
        label: 'THE LIBRARY',
        action: { type: 'go', to: 'library' },
      },
      {
        id: 'alley-stack',
        src: cut('tv-stack'),
        x: 35.6,
        y: 19.6,
        w: 28.8,
        h: 46.4,
        z: 3,
        action: { type: 'inspect', text: 'the tvs blast static. occasionally a coherent image appears...' },
      },
      {
        id: 'alley-tv-0',
        x: 38.8,
        y: 27.6,
        w: 8,
        h: 9.6,
        z: 6,
        action: { type: 'footage', n: 3 },
      },
      {
        id: 'alley-tv-1',
        x: 48.4,
        y: 30.8,
        w: 8,
        h: 9.6,
        z: 6,
        action: { type: 'footage', n: 4 },
      },
      {
        id: 'alley-tv-2',
        x: 53.2,
        y: 42,
        w: 8,
        h: 9.6,
        z: 6,
        action: { type: 'footage', n: 5 },
      },
      {
        id: 'alley-door-locked',
        src: cut('moldy-closed-door'),
        x: 78,
        y: 46,
        w: 8,
        h: 24,
        z: 2,
        visible: f => !f.venueUnlocked,
        action: { type: 'puzzle', puzzle: 'password' },
      },
      {
        id: 'alley-door-open',
        src: cut('open-molded-door'),
        x: 78,
        y: 46,
        w: 8,
        h: 24,
        z: 2,
        visible: f => f.venueUnlocked,
        action: { type: 'go', to: 'venue' },
      },
      {
        id: 'alley-scrap',
        src: cut('pile-of-scrap'),
        x: 68,
        y: 52,
        w: 22,
        h: 28,
        z: 6,
      },
      {
        id: 'alley-scrap-2a',
        src: cut('pile-of-scrap-2'),
        x: 3,
        y: 68,
        w: 16,
        h: 20,
        z: 3,
      },
      {
        id: 'alley-scrap-2b',
        src: cut('pile-of-scrap'),
        x: 10,
        y: 72,
        w: 15,
        h: 18,
        z: 4,
        flipX: true,
      },
      {
        id: 'alley-scrap-2c',
        src: cut('pile-of-scrap-2'),
        x: 6,
        y: 76,
        w: 14,
        h: 17,
        z: 5,
      },
      {
        id: 'alley-tv-old',
        src: cut('old-tv-transparent-screen'),
        x: 9.4,
        y: 84.5,
        w: 8.25,
        h: 10.5,
        z: 10,
        action: { type: 'footage', n: 7 },
      },
    ],
  },

  scrapyard: {
    id: 'scrapyard',
    title: 'THE SCRAPYARD',
    bg: bg('new-crashed-car'),
    hotspots: [
      {
        id: 'car-wreck',
        src: cut('wrecked-rusted-car'),
        x: 30,
        y: 38,
        w: 24,
        h: 20,
        z: 3,
        action: {
          type: 'inspect',
          text: 'you remember when you could buy gasoline anywhere',
        },
      },
      {
        id: 'car-green',
        src: cut('wrecked-rusted-green-car'),
        x: 50,
        y: 45,
        w: 16,
        h: 14,
        z: 2,
      },
      {
        id: 'car-blue',
        src: cut('wrecked-rusted-blue-car'),
        x: 65,
        y: 46,
        w: 14,
        h: 14,
        z: 2,
        opacity: 0.9,
        action: {
          type: 'inspect',
          text: 'you could burn it down',
        },
      },
      {
        id: 'car-red-barrel',
        src: cut('red-oil-barrel'),
        x: 10.5,
        y: 51,
        w: 5,
        h: 14,
        z: 3,
      },
      {
        id: 'car-red-barrel-2',
        src: cut('yellow-oil-barrel'),
        x: 13.2,
        y: 53,
        w: 4.6,
        h: 13,
        z: 4,
      },
      {
        id: 'car-red-barrel-3',
        src: cut('red-oil-barrel'),
        x: 8,
        y: 54,
        w: 5.2,
        h: 14.5,
        z: 5,
      },
      {
        id: 'car-yellow-barrel',
        src: cut('yellow-oil-barrel'),
        x: 81,
        y: 64,
        w: 6,
        h: 16,
        z: 6,
        action: {
          type: 'inspect',
          text: 'there\'s an engraving on the side. "Who\'s Got a Match?"',
        },
      },
      {
        id: 'car-yellow-barrel-2',
        src: cut('red-oil-barrel'),
        x: 84.5,
        y: 66,
        w: 5.4,
        h: 14.8,
        z: 7,
        action: {
          type: 'inspect',
          text: 'there\'s an engraving on the side. "Who\'s Got a Match?"',
        },
      },
      {
        id: 'car-yellow-barrel-3',
        src: cut('yellow-oil-barrel'),
        x: 78.2,
        y: 67,
        w: 5.8,
        h: 15.5,
        z: 8,
        action: {
          type: 'inspect',
          text: 'there\'s an engraving on the side. "Who\'s Got a Match?"',
        },
      },
      {
        id: 'car-matchbox',
        src: cut('match-box'),
        x: 44.4,
        y: 69.6,
        w: 5.25,
        h: 3.75,
        z: 7,
        rotate: -30,
        visible: f => !f.hasMatchbook,
        action: {
          type: 'flag',
          flag: 'hasMatchbook',
          text: 'a matchbook, you pocket it for later',
        },
      },
    ],
  },

  chapel: {
    id: 'chapel',
    title: 'SPIRAL CHAPEL',
    bg: bg('spiral-chapel'),
    hotspots: [
      {
        id: 'chapel-angel',
        src: cut('gothic-angel-statue'),
        x: 37,
        y: 16,
        w: 26,
        h: 68,
        z: 3,
        action: {
          type: 'inspect',
          text: 'when you meet your maker you will find out he is the taker.',
        },
      },
      {
        id: 'chapel-spiral',
        src: `${PROC}/wgam-spiral-icon-animated.svg`,
        x: 43,
        y: 4,
        w: 14,
        h: 22,
        z: 5,
        spin: true,
        action: { type: 'invert' },
      },
      {
        id: 'chapel-bones-b1',
        src: cut('pile-of-bones'),
        x: 4,
        y: 73,
        w: 16,
        h: 23,
        z: 2,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-b2',
        src: cut('pile-of-bones'),
        x: 18,
        y: 75,
        w: 15,
        h: 21,
        z: 2,
        flipX: true,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-b3',
        src: cut('pile-of-bones'),
        x: 32,
        y: 72,
        w: 18,
        h: 25,
        z: 1,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-b4',
        src: cut('pile-of-bones'),
        x: 46,
        y: 76,
        w: 16,
        h: 21,
        z: 2,
        flipX: true,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-b5',
        src: cut('pile-of-bones'),
        x: 60,
        y: 73,
        w: 17,
        h: 23,
        z: 1,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-b6',
        src: cut('pile-of-bones'),
        x: 74,
        y: 75,
        w: 15,
        h: 21,
        z: 2,
        flipX: true,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-b7',
        src: cut('pile-of-bones'),
        x: 86,
        y: 71,
        w: 18,
        h: 25,
        z: 1,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-1',
        src: cut('pile-of-bones'),
        x: -4,
        y: 76,
        w: 20,
        h: 28,
        z: 6,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-2',
        src: cut('pile-of-bones'),
        x: 10,
        y: 78,
        w: 18,
        h: 26,
        z: 8,
        flipX: true,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-3',
        src: cut('pile-of-bones'),
        x: 24,
        y: 75,
        w: 22,
        h: 30,
        z: 5,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-4',
        src: cut('pile-of-bones'),
        x: 38,
        y: 79,
        w: 19,
        h: 25,
        z: 9,
        flipX: true,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-5',
        src: cut('pile-of-bones'),
        x: 52,
        y: 76,
        w: 21,
        h: 28,
        z: 6,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-6',
        src: cut('pile-of-bones'),
        x: 66,
        y: 78,
        w: 18,
        h: 26,
        z: 8,
        flipX: true,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-7',
        src: cut('pile-of-bones'),
        x: 78,
        y: 74,
        w: 22,
        h: 30,
        z: 4,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
      {
        id: 'chapel-bones-8',
        src: cut('pile-of-bones'),
        x: 90,
        y: 77,
        w: 16,
        h: 26,
        z: 7,
        flipX: true,
        action: {
          type: 'inspect',
          text: 'first death when you drop. second in the dirt. third when the name is gone.',
        },
      },
    ],
  },

  venue: {
    id: 'venue',
    title: 'THE VENUE',
    bg: bg('the-venue'),
    hotspots: [
      {
        id: 'venue-spiral',
        src: `${PROC}/wgam-spiral-icon-animated.svg`,
        x: 36,
        y: 4,
        w: 28,
        h: 48,
        z: 1,
        spin: true,
        className: 'world-club-spiral',
        action: { type: 'inspect', text: 'under the spiral. sunday. they found you.' },
      },
      {
        id: 'venue-body-1',
        src: cut('guitarist-silhouette'),
        x: 39,
        y: 35,
        w: 8.2,
        h: 22.5,
        z: 3,
        action: { type: 'inspect', text: 'guitar. lead vox. match.' },
      },
      {
        id: 'venue-rabbit-1',
        src: cut('white-rabbit-mask'),
        x: 39.6,
        y: 32.9,
        w: 6.1,
        h: 10.9,
        z: 4,
        flipX: true,
        rotate: 15,
        action: { type: 'inspect', text: 'guitar. lead vox. match.' },
      },
      {
        id: 'venue-body-2',
        src: cut('singer-silhouette'),
        x: 45.5,
        y: 36,
        w: 11,
        h: 32,
        z: 6,
        action: { type: 'inspect', text: 'bass. backing vox. no names here.' },
      },
      {
        id: 'venue-rabbit-2',
        src: cut('white-rabbit-mask'),
        x: 47.7,
        y: 30.1,
        w: 6.2,
        h: 11,
        z: 7,
        rotate: -5,
        filter: 'contrast(1.15) brightness(0.9)',
        action: { type: 'inspect', text: 'bass. backing vox. no names here.' },
      },
      {
        id: 'venue-body-3',
        src: cut('guitar-silhouette-2'),
        x: 53,
        y: 35,
        w: 11.2,
        h: 24.5,
        z: 3,
        flipX: true,
        action: { type: 'inspect', text: 'drums. the pulse under the doctrine.' },
      },
      {
        id: 'venue-rabbit-3',
        src: cut('white-rabbit-mask'),
        x: 57.9,
        y: 30.3,
        w: 5.2,
        h: 9.2,
        z: 4,
        rotate: 10,
        filter: 'grayscale(0.4)',
        action: { type: 'inspect', text: 'drums. the pulse under the doctrine.' },
      },
      {
        id: 'venue-glyph',
        src: `${PROC}/wgam-spiral-icon.webp`,
        x: 8,
        y: 70,
        w: 8,
        h: 12,
        z: 6,
        opacity: 0.8,
        visible: f => f.glyphUnlocked,
        action: {
          type: 'inspect',
          text: 'the three screens remembered you. do you want to dream with me?',
        },
      },
      {
        id: 'venue-striker',
        x: 26,
        y: 74,
        w: 48,
        h: 24,
        z: 8,
        action: { type: 'puzzle', puzzle: 'strike' },
      },
    ],
  },

  fire: {
    id: 'fire',
    title: 'THE FIRE',
    bg: bg('the-fire'),
    hotspots: [
      {
        id: 'fire-glob',
        src: `${PROC}/animated-black-splotch.webp`,
        x: 12,
        y: 8,
        w: 76,
        h: 72,
        z: 1,
        behind: true,
        opacity: 0.55,
      },
      {
        id: 'fire-back-l',
        src: cut('camp-fire'),
        x: 8,
        y: 18,
        w: 20,
        h: 44,
        z: 3,
        opacity: 0.75,
      },
      {
        id: 'fire-back-r',
        src: cut('camp-fire'),
        x: 70,
        y: 18,
        w: 20,
        h: 44,
        z: 3,
        flipX: true,
        opacity: 0.75,
      },
      {
        id: 'fire-mid',
        src: cut('camp-fire'),
        x: 36,
        y: 28,
        w: 28,
        h: 54,
        z: 5,
      },
      {
        id: 'fire-mid-l',
        src: cut('fire-1'),
        x: 14,
        y: 36,
        w: 26,
        h: 46,
        z: 6,
        opacity: 0.85,
      },
      {
        id: 'fire-mid-r',
        src: cut('fire-1'),
        x: 58,
        y: 36,
        w: 26,
        h: 46,
        z: 6,
        flipX: true,
        opacity: 0.85,
      },
      {
        id: 'fire-front',
        src: cut('wide-fire'),
        x: -4,
        y: 50,
        w: 108,
        h: 56,
        z: 8,
      },
    ],
  },
}

export function sceneHotspots(id: LocationId, flags: Flags) {
  return SCENES[id].hotspots.filter(h => (h.visible ? h.visible(flags) : true))
}

export const DOCTRINE_TEXT =
  'it says "The Spiral Doctrine of 2071. When you are born you are given a job. You do that job for the rest of your life. You have no choice. A spiral appears in the center of the room."'

const PARENT: Record<LocationId, LocationId | null> = {
  map: null,
  tents: 'map',
  screen: 'map',
  scrapyard: 'map',
  alley: 'map',
  library: 'alley',
  chapel: 'library',
  venue: 'alley',
  fire: 'venue',
}

export function parentOf(id: LocationId): LocationId | null {
  return PARENT[id]
}
