// All real EPK copy and asset references live here so the layout components
// stay free of content. Photo URLs come from photos.json, which is generated
// by `npm run photos:upload` (see scripts/upload-photos.mjs).
import photosJson from './photos.json'
import videoJson from './video.json'

export const BIO_PARAGRAPHS = [
  'New York\u2019s hottest power trio, Who\u2019s Got a Match, channels the alternative rock power of bands like The Smashing Pumpkins, Muse, and Nine Inch Nails, while amping up the theatrics with blistering riffs and unmatched energy. Discovered in 2025 by producer PJ Bianco (A R I Z O N A, Jonas Brothers, Demi Lovato), the band has been diligently working on their debut EP, set for release in January 2027.',
  'The band was born after singer-songwriter "Match" survived a near-fatal health scare. Following the incident, he felt as though he had awoken in a strange new world that he neither understood nor wanted to understand. A chance meeting with PJ Bianco planted the seeds for what would ultimately become the band. After writing over 100 songs in a single year, they finally selected the tracks for their upcoming EP.',
  '"When I woke up in the hospital, I knew I had to pursue the dreams I had always put off," Match states. "Songwriting suddenly went from a hobby to an obsession. Sleep became secondary to dissecting my favorite songs and figuring out what makes them tick. This obsession took over my life, and honestly, I don\u2019t see it ever ending. When I met the rest of the guys, it felt like fate. And now, here we are\u2014for your pleasure or displeasure.',
  '"My main idea was: What if Billy Corgan and Trent Reznor walked into a room and wrote a song? That concept slowly evolved as I threw more elements into my Willy Wonka machine. All I knew was that very few rock artists have truly inspired me in the past few years. I\u2019m so tired of hearing some rich kid sing about the hardships of life, or listening to some famous person\'s kid, or some industry plant. Where are the Nirvanas of today who came from nothing and speak for the people? Do we really give a shit about what some 1% rich kid has to say about life? Because I sure as hell don\u2019t. That person has no conception of the average person\'s reality. This music is born from not just feeling like an outsider, but knowing you are different from other people. Sooner or later, you realize that difference is a power. If you use it, it becomes a superpower.',
  '"I am just another rat in a race for rats to die. I decided to break the cycle and pave my own path, and I hope my music inspires people to do the same. We aim to bring something that will inspire people the same way my favorite bands inspired me the first time I heard them. But the music alone isn\u2019t enough. We aim to visually warp people\'s minds and deliver a live show that rivals bands ten times our size. We aren\'t content with just staying in NYC; we intend to chew through the cartilage and see what\'s outside of this place. Life\'s short, folks. Better listen to something good before the lights go out."',
]

export const BIO_SIGNOFF = ['Till next time\u2026', 'Rats']

/** Short excerpt shown in the bio cell before "READ FULL BIO". */
export const BIO_EXCERPT = BIO_PARAGRAPHS[0]

export type Track = {
  id: string
  title: string
  src: string
  /** seconds, from ffprobe */
  duration: number
}

export const TRACKS: Track[] = [
  { id: 'bellyaching', title: 'Bellyaching', src: '/audio/demos/bellyaching.mp3', duration: 178 },
  { id: 'i-dont-care', title: "I Don't Care", src: '/audio/demos/i-dont-care.mp3', duration: 215 },
  {
    id: 'little-white-pills',
    title: 'Little White Pills',
    src: '/audio/demos/little-white-pills.mp3',
    duration: 212,
  },
  {
    id: 'new-crashed-car',
    title: 'New Crashed Car',
    src: '/audio/demos/new-crashed-car.mp3',
    duration: 190,
  },
]

/** Track that starts playing when the EPK is entered. */
export const BACKGROUND_TRACK_ID = 'little-white-pills'

export function formatDuration(seconds: number) {
  const s = Math.max(0, Math.round(seconds))
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`
}

/** Web encode + poster on Vercel Blob, generated by `npm run video:upload`. */
export const MUSIC_VIDEO = videoJson

export const PRESS_QUOTE = {
  text: 'It\u2019s a mix between Smashing Pumpkins and Depeche Mode, I love it.',
  author: 'Justin Hawkins',
  role: 'The Darkness',
}

export const CONTACT = {
  email: 'whosgotamatchband@gmail.com',
  phoneDisplay: '+1 (845) 233-1218',
  phoneHref: 'tel:+18452331218',
  location: 'New York City, NY',
}

export type PhotoAsset = {
  url: string
  bytes: number
  width: number
  height: number
}

export type Photo = {
  id: string
  original: PhotoAsset
  preview: PhotoAsset
  thumb: PhotoAsset
}

export const PHOTOS: Photo[] = photosJson

export function formatBytes(bytes: number) {
  const mb = bytes / (1024 * 1024)
  return mb >= 10 ? `${Math.round(mb)} MB` : `${mb.toFixed(1)} MB`
}

/** Vercel Blob honours ?download=1 by setting Content-Disposition: attachment. */
export function downloadUrl(asset: PhotoAsset) {
  return `${asset.url}?download=1`
}
